version: "3.9"

networks:
  app-tier:
    driver: bridge

volumes:
  storage_data:


services:
  minio:
    image: minio/minio:latest
    ports:
      - "3000:3000"
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=username
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - storage_data:/data
    command: server /data --console-address ":3000" --address :9000
